# Task - configure cloudhealth agent
---
- name: Ensure the agent is installed
  command:
    curl https://s3.amazonaws.com/remote-collector/agent/v18/install_cht_perfmon.sh -o /tmp/install_cht_perfmon.sh -s &&
    /tmp/install_cht_perfmon.sh 18 {{ cht_unique_registration_code }} aws
  args:
    creates: /opt/cht_perfmon
  sudo: yes
