---
# file: base-ami.yml
- name: Configure and deploy base AMI
  hosts: 127.0.0.1
  connection: local
  remote_user: ubuntu
  become: yes
  gather_facts: False
  roles:
    - python
    - hosts
    - base-ami
    - cloudhealth-agent
