---
# file: packer/kube.yml
- name: Configure and deploy kube node
  hosts: tag_Name_{{ tag_name }}_{{ tag_environment }}
  remote_user: ubuntu
  become: yes
  gather_facts: False
  roles:
    - python
    - hosts
    - kube-slave

