---
# Variables for ec2 role

key_name: "{{ lookup('env','SSH_KEY') }}"
security_group: "{{ lookup('env','SG_ID') }}"
type: "t2.micro"
ami_id: "{{ lookup('env','AMI_ID') }}"
subnet_id: "{{ lookup('env','SUBNET_ID') }}"
tag_name: "{{ lookup('env','TAG_NAME') }}"
tag_environment: "{{ lookup('env','TAG_ENV') }}"
count: 1
region: "us-east-1"
iam_role: "{{ lookup('env','IAM_ROLE') }}"
storage: "8"

