# Task - slave
# Configure server to increase file limits / handles

- name: Copy over limits
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: 0644

- name: Copy over common sessions file
  copy:
    src: common-session
    dest: /etc/pam.d/common-session
    owner: root
    group: root
    mode: 0644


- name: Copy over common sessions file
  copy:
    src: common-session
    dest: /etc/pam.d/common-session-noninteractive 
    owner: root
    group: root
    mode: 0644
