# Task - slave
# Configure server to increase file limits / handles

- name: Copy over limits
  template: src=limits.conf.j2 dest=/etc/security/limits.conf  mode=0644 owner=root

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present
    install_recommends: yes

- name: Install Auditd apt packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes 
  with_items:
       - auditd
       - audispd-plugins

- name: Copy 20auto-upgrades file to proper place
  become: yes
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Update from distros
  become: yes
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
