# Task - slave
# Configure server to increase file limits / handles

- name: Copy over limits
  template: src=limits.conf.j2 dest=/etc/security/limits.conf  mode=0644 owner=root

- name: Copy over common sessions file
  become: yes
  copy:
    src: common-session
    dest: /etc/pam.d/common-session
    owner: root
    group: root
    mode: 0644


- name: Copy over common sessions file
  become: yes
  copy:
    src: common-session
    dest: /etc/pam.d/common-session-noninteractive 
    owner: root
    group: root
    mode: 0644

- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present
    install_recommends: yes

- name: Copy 20auto-upgrades file to proper place
  become: yes
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Enable unattended-upgrades
  command: sudo dpkg-reconfigure -f noninteractive unattended-upgrades

- name: Ensure the agent is installed
  command: "{{item}}"
  args:
    creates: /opt/cht_perfmon
  sudo: yes
  with_items:
       - wget https://s3.amazonaws.com/remote-collector/agent/v18/install_cht_perfmon.sh -O /tmp/install_cht_perfmon.sh
       - /tmp/install_cht_perfmon.sh 19 {{ cht_unique_registration_code }} aws
