# Task - slave
# Configure server to increase file limits / handles

- name: Copy over limits
  template: src=limits.conf.j2 dest=/etc/security/limits.conf  mode=0644 owner=root

- name: Copy over common sessions file
  become: yes
  copy:
    src: common-session
    dest: /etc/pam.d/common-session
    owner: root
    group: root
    mode: 0644


- name: Copy over common sessions file
  become: yes
  copy:
    src: common-session
    dest: /etc/pam.d/common-session-noninteractive 
    owner: root
    group: root
    mode: 0644

- name: Inttall unattended-upgrades
  apt:
    name: unattended-upgrades
    state: present
    install_recommends: yes

- name: Enable unattended-upgrades
  shell: dpkg-reconfigure unattended-upgrades
  args:
    executable: /bin/bash
  become: yes
