---
# Variables for ec2 role

org_country: "{{ lookup('env','ORG_COUNTRY') }}"
org_province: "{{ lookup('env','ORG_PROVINCE') }}"
org_location: "{{ lookup('env','ORG_LOCATION') }}"
org_name: "{{ lookup('env','ORG_NAME') }}"
